name: CI

on:
  push:

permissions:
  contents: read
  packages: write

jobs:
  lint:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: hadolint/hadolint-action@v3.1.0
          with:
            dockerfile: Dockerfile
  build:
    name: Test Docker build
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: my-docker-hub-namespace/my-docker-hub-repository:latest
  publish:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: [lint, build]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/jmgilman/argo-cmp-timoni
      - name: Build and publish Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}